# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'home.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(800, 480)
        self.horizontalLayout = QHBoxLayout(Form)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.groupBox = QGroupBox(Form)
        self.groupBox.setObjectName(u"groupBox")
        self.verticalLayout = QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.splitter = QSplitter(self.groupBox)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Horizontal)
        self.label = QLabel(self.splitter)
        self.label.setObjectName(u"label")
        self.label.setMinimumSize(QSize(20, 0))
        self.label.setMaximumSize(QSize(20, 16777215))
        self.label.setAlignment(Qt.AlignCenter)
        self.splitter.addWidget(self.label)
        self.lineEdit_1 = QLineEdit(self.splitter)
        self.lineEdit_1.setObjectName(u"lineEdit_1")
        self.splitter.addWidget(self.lineEdit_1)
        self.pushButton_1 = QPushButton(self.splitter)
        self.pushButton_1.setObjectName(u"pushButton_1")
        self.pushButton_1.setMaximumSize(QSize(60, 16777215))
        self.splitter.addWidget(self.pushButton_1)

        self.verticalLayout.addWidget(self.splitter)

        self.splitter_2 = QSplitter(self.groupBox)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setOrientation(Qt.Horizontal)
        self.label_2 = QLabel(self.splitter_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setMinimumSize(QSize(20, 0))
        self.label_2.setMaximumSize(QSize(20, 16777215))
        self.label_2.setAlignment(Qt.AlignCenter)
        self.splitter_2.addWidget(self.label_2)
        self.lineEdit_2 = QLineEdit(self.splitter_2)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.splitter_2.addWidget(self.lineEdit_2)
        self.pushButton_2 = QPushButton(self.splitter_2)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setMaximumSize(QSize(60, 16777215))
        self.splitter_2.addWidget(self.pushButton_2)

        self.verticalLayout.addWidget(self.splitter_2)

        self.splitter_3 = QSplitter(self.groupBox)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setOrientation(Qt.Horizontal)
        self.label_3 = QLabel(self.splitter_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setMinimumSize(QSize(20, 0))
        self.label_3.setMaximumSize(QSize(20, 16777215))
        self.label_3.setAlignment(Qt.AlignCenter)
        self.splitter_3.addWidget(self.label_3)
        self.lineEdit_3 = QLineEdit(self.splitter_3)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.splitter_3.addWidget(self.lineEdit_3)
        self.pushButton_3 = QPushButton(self.splitter_3)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setMaximumSize(QSize(60, 16777215))
        self.splitter_3.addWidget(self.pushButton_3)

        self.verticalLayout.addWidget(self.splitter_3)

        self.splitter_4 = QSplitter(self.groupBox)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setOrientation(Qt.Horizontal)
        self.label_4 = QLabel(self.splitter_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setMinimumSize(QSize(20, 0))
        self.label_4.setMaximumSize(QSize(20, 16777215))
        self.label_4.setAlignment(Qt.AlignCenter)
        self.splitter_4.addWidget(self.label_4)
        self.lineEdit_4 = QLineEdit(self.splitter_4)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.splitter_4.addWidget(self.lineEdit_4)
        self.pushButton_4 = QPushButton(self.splitter_4)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setMaximumSize(QSize(60, 16777215))
        self.splitter_4.addWidget(self.pushButton_4)

        self.verticalLayout.addWidget(self.splitter_4)

        self.splitter_5 = QSplitter(self.groupBox)
        self.splitter_5.setObjectName(u"splitter_5")
        self.splitter_5.setOrientation(Qt.Horizontal)
        self.label_5 = QLabel(self.splitter_5)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setMinimumSize(QSize(20, 0))
        self.label_5.setMaximumSize(QSize(20, 16777215))
        self.label_5.setAlignment(Qt.AlignCenter)
        self.splitter_5.addWidget(self.label_5)
        self.lineEdit_5 = QLineEdit(self.splitter_5)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.splitter_5.addWidget(self.lineEdit_5)
        self.pushButton_5 = QPushButton(self.splitter_5)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setMaximumSize(QSize(60, 16777215))
        self.splitter_5.addWidget(self.pushButton_5)

        self.verticalLayout.addWidget(self.splitter_5)

        self.splitter_6 = QSplitter(self.groupBox)
        self.splitter_6.setObjectName(u"splitter_6")
        self.splitter_6.setOrientation(Qt.Horizontal)
        self.label_6 = QLabel(self.splitter_6)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setMinimumSize(QSize(20, 0))
        self.label_6.setMaximumSize(QSize(20, 16777215))
        self.label_6.setAlignment(Qt.AlignCenter)
        self.splitter_6.addWidget(self.label_6)
        self.lineEdit_6 = QLineEdit(self.splitter_6)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.splitter_6.addWidget(self.lineEdit_6)
        self.pushButton_6 = QPushButton(self.splitter_6)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setMaximumSize(QSize(60, 16777215))
        self.splitter_6.addWidget(self.pushButton_6)

        self.verticalLayout.addWidget(self.splitter_6)

        self.splitter_7 = QSplitter(self.groupBox)
        self.splitter_7.setObjectName(u"splitter_7")
        self.splitter_7.setOrientation(Qt.Horizontal)
        self.label_7 = QLabel(self.splitter_7)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setMinimumSize(QSize(20, 0))
        self.label_7.setMaximumSize(QSize(20, 16777215))
        self.label_7.setAlignment(Qt.AlignCenter)
        self.splitter_7.addWidget(self.label_7)
        self.lineEdit_7 = QLineEdit(self.splitter_7)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.splitter_7.addWidget(self.lineEdit_7)
        self.pushButton_7 = QPushButton(self.splitter_7)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setMaximumSize(QSize(60, 16777215))
        self.splitter_7.addWidget(self.pushButton_7)

        self.verticalLayout.addWidget(self.splitter_7)

        self.splitter_8 = QSplitter(self.groupBox)
        self.splitter_8.setObjectName(u"splitter_8")
        self.splitter_8.setOrientation(Qt.Horizontal)
        self.label_8 = QLabel(self.splitter_8)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setMinimumSize(QSize(20, 0))
        self.label_8.setMaximumSize(QSize(20, 16777215))
        self.label_8.setAlignment(Qt.AlignCenter)
        self.splitter_8.addWidget(self.label_8)
        self.lineEdit_8 = QLineEdit(self.splitter_8)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.splitter_8.addWidget(self.lineEdit_8)
        self.pushButton_8 = QPushButton(self.splitter_8)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setMaximumSize(QSize(60, 16777215))
        self.splitter_8.addWidget(self.pushButton_8)

        self.verticalLayout.addWidget(self.splitter_8)

        self.splitter_9 = QSplitter(self.groupBox)
        self.splitter_9.setObjectName(u"splitter_9")
        self.splitter_9.setOrientation(Qt.Horizontal)
        self.label_9 = QLabel(self.splitter_9)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setMinimumSize(QSize(20, 0))
        self.label_9.setMaximumSize(QSize(20, 16777215))
        self.label_9.setAlignment(Qt.AlignCenter)
        self.splitter_9.addWidget(self.label_9)
        self.lineEdit_9 = QLineEdit(self.splitter_9)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.splitter_9.addWidget(self.lineEdit_9)
        self.pushButton_9 = QPushButton(self.splitter_9)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setMaximumSize(QSize(60, 16777215))
        self.splitter_9.addWidget(self.pushButton_9)

        self.verticalLayout.addWidget(self.splitter_9)

        self.splitter_10 = QSplitter(self.groupBox)
        self.splitter_10.setObjectName(u"splitter_10")
        self.splitter_10.setOrientation(Qt.Horizontal)
        self.label_10 = QLabel(self.splitter_10)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setMinimumSize(QSize(20, 0))
        self.label_10.setMaximumSize(QSize(20, 16777215))
        self.label_10.setAlignment(Qt.AlignCenter)
        self.splitter_10.addWidget(self.label_10)
        self.lineEdit_10 = QLineEdit(self.splitter_10)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.splitter_10.addWidget(self.lineEdit_10)
        self.pushButton_10 = QPushButton(self.splitter_10)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setMaximumSize(QSize(60, 16777215))
        self.splitter_10.addWidget(self.pushButton_10)

        self.verticalLayout.addWidget(self.splitter_10)

        self.splitter_11 = QSplitter(self.groupBox)
        self.splitter_11.setObjectName(u"splitter_11")
        self.splitter_11.setOrientation(Qt.Horizontal)
        self.label_11 = QLabel(self.splitter_11)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setMinimumSize(QSize(20, 0))
        self.label_11.setMaximumSize(QSize(20, 16777215))
        self.label_11.setAlignment(Qt.AlignCenter)
        self.splitter_11.addWidget(self.label_11)
        self.lineEdit_11 = QLineEdit(self.splitter_11)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.splitter_11.addWidget(self.lineEdit_11)
        self.pushButton_11 = QPushButton(self.splitter_11)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setMaximumSize(QSize(60, 16777215))
        self.splitter_11.addWidget(self.pushButton_11)

        self.verticalLayout.addWidget(self.splitter_11)

        self.splitter_12 = QSplitter(self.groupBox)
        self.splitter_12.setObjectName(u"splitter_12")
        self.splitter_12.setOrientation(Qt.Horizontal)
        self.label_12 = QLabel(self.splitter_12)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setMinimumSize(QSize(20, 0))
        self.label_12.setMaximumSize(QSize(20, 16777215))
        self.label_12.setAlignment(Qt.AlignCenter)
        self.splitter_12.addWidget(self.label_12)
        self.lineEdit_12 = QLineEdit(self.splitter_12)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.splitter_12.addWidget(self.lineEdit_12)
        self.pushButton_12 = QPushButton(self.splitter_12)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setMaximumSize(QSize(60, 16777215))
        self.splitter_12.addWidget(self.pushButton_12)

        self.verticalLayout.addWidget(self.splitter_12)

        self.splitter_13 = QSplitter(self.groupBox)
        self.splitter_13.setObjectName(u"splitter_13")
        self.splitter_13.setOrientation(Qt.Horizontal)
        self.label_13 = QLabel(self.splitter_13)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setMinimumSize(QSize(20, 0))
        self.label_13.setMaximumSize(QSize(20, 16777215))
        self.label_13.setAlignment(Qt.AlignCenter)
        self.splitter_13.addWidget(self.label_13)
        self.lineEdit_13 = QLineEdit(self.splitter_13)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.splitter_13.addWidget(self.lineEdit_13)
        self.pushButton_13 = QPushButton(self.splitter_13)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setMaximumSize(QSize(60, 16777215))
        self.splitter_13.addWidget(self.pushButton_13)

        self.verticalLayout.addWidget(self.splitter_13)

        self.splitter_14 = QSplitter(self.groupBox)
        self.splitter_14.setObjectName(u"splitter_14")
        self.splitter_14.setOrientation(Qt.Horizontal)
        self.label_14 = QLabel(self.splitter_14)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setMinimumSize(QSize(20, 0))
        self.label_14.setMaximumSize(QSize(20, 16777215))
        self.label_14.setAlignment(Qt.AlignCenter)
        self.splitter_14.addWidget(self.label_14)
        self.lineEdit_14 = QLineEdit(self.splitter_14)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.splitter_14.addWidget(self.lineEdit_14)
        self.pushButton_14 = QPushButton(self.splitter_14)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setMaximumSize(QSize(60, 16777215))
        self.splitter_14.addWidget(self.pushButton_14)

        self.verticalLayout.addWidget(self.splitter_14)

        self.splitter_15 = QSplitter(self.groupBox)
        self.splitter_15.setObjectName(u"splitter_15")
        self.splitter_15.setOrientation(Qt.Horizontal)
        self.label_15 = QLabel(self.splitter_15)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setMinimumSize(QSize(20, 0))
        self.label_15.setMaximumSize(QSize(20, 16777215))
        self.label_15.setAlignment(Qt.AlignCenter)
        self.splitter_15.addWidget(self.label_15)
        self.lineEdit_15 = QLineEdit(self.splitter_15)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.splitter_15.addWidget(self.lineEdit_15)
        self.pushButton_15 = QPushButton(self.splitter_15)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setMaximumSize(QSize(60, 16777215))
        self.splitter_15.addWidget(self.pushButton_15)

        self.verticalLayout.addWidget(self.splitter_15)


        self.horizontalLayout.addWidget(self.groupBox)

        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.groupBox_2 = QGroupBox(Form)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.verticalLayout_2 = QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.splitter_16 = QSplitter(self.groupBox_2)
        self.splitter_16.setObjectName(u"splitter_16")
        self.splitter_16.setOrientation(Qt.Horizontal)
        self.label_16 = QLabel(self.splitter_16)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setMinimumSize(QSize(40, 0))
        self.label_16.setMaximumSize(QSize(60, 16777215))
        self.label_16.setAlignment(Qt.AlignCenter)
        self.splitter_16.addWidget(self.label_16)
        self.export_edit = QLineEdit(self.splitter_16)
        self.export_edit.setObjectName(u"export_edit")
        self.splitter_16.addWidget(self.export_edit)
        self.export_select_btn = QPushButton(self.splitter_16)
        self.export_select_btn.setObjectName(u"export_select_btn")
        self.export_select_btn.setMaximumSize(QSize(60, 16777215))
        self.splitter_16.addWidget(self.export_select_btn)

        self.verticalLayout_2.addWidget(self.splitter_16)

        self.splitter_17 = QSplitter(self.groupBox_2)
        self.splitter_17.setObjectName(u"splitter_17")
        self.splitter_17.setOrientation(Qt.Horizontal)
        self.label_17 = QLabel(self.splitter_17)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setMinimumSize(QSize(100, 0))
        self.label_17.setMaximumSize(QSize(16777215, 16777215))
        self.label_17.setAlignment(Qt.AlignCenter)
        self.splitter_17.addWidget(self.label_17)
        self.generate_amount_edit = QLineEdit(self.splitter_17)
        self.generate_amount_edit.setObjectName(u"generate_amount_edit")
        self.splitter_17.addWidget(self.generate_amount_edit)

        self.verticalLayout_2.addWidget(self.splitter_17)

        self.start_button = QPushButton(self.groupBox_2)
        self.start_button.setObjectName(u"start_button")

        self.verticalLayout_2.addWidget(self.start_button)


        self.verticalLayout_4.addWidget(self.groupBox_2)

        self.groupBox_3 = QGroupBox(Form)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.verticalLayout_3 = QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.log_listWidget = QListWidget(self.groupBox_3)
        self.log_listWidget.setObjectName(u"log_listWidget")

        self.verticalLayout_3.addWidget(self.log_listWidget)


        self.verticalLayout_4.addWidget(self.groupBox_3)


        self.horizontalLayout.addLayout(self.verticalLayout_4)


        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"\u89c6\u9891\u6279\u91cf\u526a\u8f91\u5de5\u5177   \u00a9AI\u5e2e  @\u6709\u9738\u592b", None))
        self.groupBox.setTitle(QCoreApplication.translate("Form", u"\u89c6\u9891\u7d20\u6750\u5207\u7247\u9009\u62e9", None))
        self.label.setText(QCoreApplication.translate("Form", u"1", None))
        self.pushButton_1.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"2", None))
        self.pushButton_2.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"3", None))
        self.pushButton_3.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"4", None))
        self.pushButton_4.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"5", None))
        self.pushButton_5.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"6", None))
        self.pushButton_6.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"7", None))
        self.pushButton_7.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"8", None))
        self.pushButton_8.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"9", None))
        self.pushButton_9.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"10", None))
        self.pushButton_10.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"11", None))
        self.pushButton_11.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"12", None))
        self.pushButton_12.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"13", None))
        self.pushButton_13.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"14", None))
        self.pushButton_14.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"15", None))
        self.pushButton_15.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Form", u"\u89c6\u9891\u5bfc\u51fa\u8bbe\u7f6e", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"\u4fdd\u5b58\u5230:", None))
        self.export_select_btn.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"\u672c\u6b21\u8981\u751f\u6210\u7684\u89c6\u9891\u6570\u91cf\uff1a", None))
        self.generate_amount_edit.setText(QCoreApplication.translate("Form", u"200", None))
        self.start_button.setText(QCoreApplication.translate("Form", u"\u5f00\u59cb\u6279\u91cf\u751f\u4ea7\u89c6\u9891", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Form", u"\u65e5\u5fd7", None))
    # retranslateUi

